apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observ
  labels:
    app: otel-collector
data:
  config.yml: |-
    receivers:
      otlp:
        protocols:
          grpc:

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        resource_to_telemetry_conversion:
          enabled: true

    processors:
      batch:
    
    service:
      extensions: []
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
