apiVersion: v1
data:
  pythonunbuffered: '1'
  worker_class: uvicorn.workers.UvicornH11Worker
kind: ConfigMap
metadata:
  name: indexer-configmap
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: indexer
  name: indexer
  namespace: default
spec:
  ports:
  - name: port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: indexer
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: indexer
        jina_deployment_name: indexer
        ns: default
        pod_type: WORKER
        shard_id: '0'
    spec:
      nodeName: gtue-desktop
      containers:
      - args:
        - executor
        - --name
        - indexer
        - --k8s-namespace
        - default
        - --uses
        - config.yml
        - --host
        - 0.0.0.0
        - --port
        - '8080'
        - --port-monitoring
        - '9090'
        - --uses-metas
        - '{}'
        - --native
        command:
        - jina
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: JINA_DEPLOYMENT_NAME
          value: indexer
        - name: K8S_DEPLOYMENT_NAME
          value: indexer
        - name: K8S_NAMESPACE_NAME
          value: default
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: indexer-configmap
        image: gabbro:30500/jina/indexer
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 2
        livenessProbe:
          exec:
            command:
            - jina
            - ping
            - executor
            - grpc://127.0.0.1:8080
            - --timeout 9500
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 10
        name: executor
        ports:
        - containerPort: 8080
        startupProbe:
          exec:
            command:
            - jina
            - ping
            - executor
            - grpc://127.0.0.1:8080
          failureThreshold: 120
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
