apiVersion: v1
kind: Service
metadata:
  name: clip-encoder
spec:
  selector:
    app: encoder
  ports:
    - port: 4191
      nodePort: 30191
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: clip-indexer
spec:
  selector:
    app: indexer
  ports:
    - port: 4191
      nodePort: 30192
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: clip-gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 4191
      nodePort: 30193
  type: NodePort
